#spring.datasource.url=jdbc:mysql://localhost:3306/judge_db
#After containerizing the mysql
spring.datasource.url=jdbc:mysql://mysql:3306/judge_db

spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=JudgeApiSecretKey2026@OnlineCodeJudgeSpringBootJWT123456789
jwt.expiration-ms=86400000
    
spring.jpa.open-in-view=false

#kafka config(prdoucer)
#spring.kafka.bootstrap-servers=localhost:9092
#For running in container
spring.kafka.bootstrap-servers=kafka:9092

#(consumer)
spring.kafka.consumer.group-id=api-service-group
spring.kafka.consumer.auto-offset-reset=earliest

#Redis config
#spring.data.redis.host=localhost
#For containerized application
spring.data.redis.host=redis
spring.data.redis.port=6379

app.admin.username=${ADMIN_USERNAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}